<?php
/**
 * This file was automatically generated by the Loops framework
 *
 * It should return a config for the Loops context class.
 * 
 * @link https://github.com/loopsframework/base
 */

use Loops\Config\IniConfig;

return new IniConfig(__DIR__."/config/config.ini");